##
## see http://about.travis-ci.org/docs/user/languages/python/
##

language: python
python:
  - "2.7"

# command to install dependencies
install:
  - "make all"

# command to run tests
# script: nosetests -v -w tests

